version: 2

build:
  # Specific version of RTD docker image that's new enough to have Rust around
  # (so Cryptography can build from source if needed).
  # See https://github.com/readthedocs/readthedocs-docker-images
  image: "7.0"

python:
  version: 3.7
  install:
    - requirements: dev-requirements.txt
  system_packages: false

# NOTE: leaving sphinx.* alone as there's currently no way to differ the conf
# file used based on project (so cannot differentiate between www and docs).
# The web UI setting for that SHOULD take precedence?
